version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-blog
    image: django-blog
    ports:
      - '8000:8000'
    volumes:
      - ./:/djnago-next-todos
    command: python3 manage.py runserver 0.0.0.0:8000